In [ ]:
#What is a Convolutional Neural Network (CNN), and why is it used for image processing?
A CNN is a deep learning model designed for image and spatial data. It detects patterns like edges, textures, and shapes via convolution operations, making it ideal for tasks like classification, object detection, and segmentation.

In [ ]:
#What are the key components of a CNN architecture?

Convolutional layers

Activation functions (e.g., ReLU)

Pooling layers

Fully connected (dense) layers

Dropout (optional for regularization)

In [ ]:
#What is the role of the convolutional layer in CNNs?
It extracts spatial features by applying filters (kernels) that slide over input data, capturing local patterns like edges or textures.

In [ ]:
#What is a filter (kernel) in CNNs?
A small matrix (e.g., 3x3) used in convolutional layers to detect specific features like horizontal edges or corners by performing element-wise multiplication and summing.

In [ ]:
#What is pooling in CNNs, and why is it important?
Pooling reduces the spatial size of feature maps to decrease computation and overfitting. It also retains dominant features.

In [ ]:
#What are the common types of pooling used in CNNs?

Max Pooling (takes the maximum value)

Average Pooling (takes the average value)

In [ ]:
#How does the backpropagation algorithm work in CNNs?
It computes gradients of loss w.r.t. weights using the chain rule and updates weights via gradient descent. It includes partial derivatives through convolutional and pooling layers.

In [ ]:
#What is the role of activation functions in CNNs?
They introduce non-linearity, allowing the network to learn complex patterns. Common activations: ReLU, sigmoid, tanh.

In [ ]:
#What is the concept of receptive fields in CNNs?
The receptive field is the region of the input image that a neuron (or feature detector) responds to. It increases with deeper layers.

In [ ]:
#xplain the concept of tensor space in CNNs.
Tensors are multi-dimensional arrays used to represent data. In CNNs, images are often represented as 4D tensors: (batch_size, height, width, channels).

In [ ]:
#What is LeNet-5, and how does it contribute to the development of CNNs?
LeNet-5 (1998) by Yann LeCun is one of the earliest CNNs, used for digit recognition. It introduced core CNN components: convolution, pooling, and fully connected layers.

In [ ]:
#What is AlexNet, and why was it a breakthrough in deep learning?
AlexNet (2012) won the ImageNet competition with a large margin. It used ReLU, dropout, and GPU training—kickstarting the deep learning revolution.

In [ ]:
#What is VGGNet, and how does it differ from AlexNet?
VGGNet (2014) uses very small filters (3x3), increasing depth (16–19 layers), and a simple, uniform architecture. It improved accuracy over AlexNet.

In [ ]:
#What is GoogLeNet, and what is its main innovation?
GoogLeNet (2014) introduced the Inception module, which uses multiple filter sizes in parallel to improve efficiency and accuracy while reducing parameters.

In [ ]:
#What is ResNet, and what problem does it solve?
ResNet (2015) introduced residual connections to mitigate the vanishing gradient problem in very deep networks. It enabled training of networks with 100+ layers.

In [ ]:
#What is DenseNet, and how does it differ from ResNet?
DenseNet connects each layer to every other layer (dense connectivity), improving gradient flow and feature reuse compared to ResNet's additive shortcuts.

In [ ]:
#What are the main steps involved in training a CNN from scratch?

Prepare the dataset (load and preprocess images)

Define CNN architecture

Choose a loss function and optimizer

Train the model (forward + backpropagation)

Evaluate performance

Fine-tune hyperparameters

Save and deploy the model

In [1]:
#Implement a basic convolution operation using a filter and a 5x5 image (matrix)
import numpy as np
image = np.random.rand(5, 5)
kernel = np.array([[1, 0, -1], [1, 0, -1], [1, 0, -1]])
result = np.zeros((3, 3))

for i in range(3):
    for j in range(3):
        result[i, j] = np.sum(image[i:i+3, j:j+3] * kernel)
print(result)


[[-0.37774586  0.3321871   0.21110546]
 [-0.63000389  0.20121012  0.02930154]
 [ 0.15693307  0.27623424 -0.20253701]]


In [3]:
# Implement max pooling on a 4x4 feature map with a 2x2 window
feature_map = np.random.rand(4, 4)
pooled = np.zeros((2, 2))

for i in range(2):
    for j in range(2):
        pooled[i, j] = np.max(feature_map[i*2:i*2+2, j*2:j*2+2])
print(pooled)

[[0.81846597 0.66651194]
 [0.77819571 0.91995115]]


In [5]:
# Implement the ReLU activation function on a feature map
feature_map = np.random.randn(3, 3)
relu_output = np.maximum(0, feature_map)
print(relu_output)

[[1.77781262 0.         0.7531494 ]
 [1.33835541 1.93390356 0.        ]
 [0.96195955 0.         0.        ]]


In [ ]:
#Create a simple CNN model with one convolutional layer and a fully connected layer, using random data
import tensorflow as tf
model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(8, (3,3), activation='relu', input_shape=(28,28,1)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(10, activation='softmax')
])
model.summary()

In [13]:
#Generate a synthetic dataset using random noise and train a simple CNN model on it
x = np.random.rand(100, 28, 28, 1)
y = tf.keras.utils.to_categorical(np.random.randint(0, 10, 100), 10)
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(x, y, epochs=3)

In [ ]:
#Create a simple CNN using Keras with one convolution layer and a max-pooling layer
model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(16, (3,3), activation='relu', input_shape=(28,28,1)),
    tf.keras.layers.MaxPooling2D((2,2)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(10, activation='softmax')
])
model.summary()

In [ ]:
#Write a code to add a fully connected layer after the convolution and max-pooling layers in a CNN
model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(32, (3,3), activation='relu', input_shape=(28,28,1)),
    tf.keras.layers.MaxPooling2D((2,2)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax')
])

In [ ]:
#Write a code to add  batch normalization to a simple CNN model
model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(32, (3,3), input_shape=(28,28,1)),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Activation('relu'),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(10, activation='softmax')
])

In [ ]:
#Write a code to add dropout regularization to a simple CNN mode|
model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(32, (3,3), activation='relu', input_shape=(28,28,1)),
    tf.keras.layers.MaxPooling2D((2,2)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(10, activation='softmax')
])

In [ ]:
#Write a code to print the architecture of the VGG16 model in Keras
from tensorflow.keras.applications import VGG16
model = VGG16()
model.summary()

In [ ]:
#Write a code to plot the accuracy and loss graphs after training a CNN model
history = model.fit(x, y, epochs=5, validation_split=0.2)

import matplotlib.pyplot as plt
plt.plot(history.history['loss'], label='loss')
plt.plot(history.history['val_loss'], label='val_loss')
plt.plot(history.history['accuracy'], label='acc')
plt.plot(history.history['val_accuracy'], label='val_acc')
plt.legend()
plt.show()


In [ ]:
#Write a code to print the architecture of the ResNet50 model in Keras
from tensorflow.keras.applications import ResNet50
model = ResNet50()
model.summary()

In [ ]:
#Write a code to train a basic CNN model and print the training loss and accuracy after each epoch
history = model.fit(x, y, epochs=5, verbose=1)